'use client';

import { useEffect, useState } from 'react';
import CodeMirror from '@uiw/react-codemirror';
import { vscodeDark } from '@uiw/codemirror-theme-vscode';
import { $typst } from '@myriaddreamin/typst.ts';
import { useDebouncedCallback } from 'use-debounce';
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import { ScrollArea } from '@/components/ui/scroll-area';

const defaultContent = `= Hello Typst!

This is a *minimal* code editor using #link("https://typst.app")[typst.ts].

== Features

- Real-time preview
- Debounced compilation
- Client-side WASM compilation

== Math Example

$ E = m c^2 $

== List Example

+ First item
+ Second item
+ Third item
`;

export default function TypstEditor() {
  const [content, setContent] = useState(defaultContent);
  const [svg, setSvg] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Initialize typst.ts
  useEffect(() => {
    const initTypst = async () => {
      try {
        console.log('Initializing Typst...');
        
        // Configure WASM paths
        $typst.setCompilerInitOptions({
          getModule: () => '/wasm/typst_ts_web_compiler_bg.wasm',
        });
        $typst.setRendererInitOptions({
          getModule: () => '/wasm/typst_ts_renderer_bg.wasm',
        });
        
        // Trigger initial compilation to test if WASM loads
        console.log('Testing compilation...');
        const testSvg = await $typst.svg({ mainContent: '= Test' });
        console.log('Test compilation successful, SVG length:', testSvg.length);
        
        setIsLoading(false);
      } catch (err) {
        console.error('Failed to initialize Typst:', err);
        setError(err instanceof Error ? err.message : 'Failed to initialize Typst compiler');
        setIsLoading(false);
      }
    };

    initTypst();
  }, []);

  // Debounced compilation
  const compile = useDebouncedCallback(async (source: string) => {
    try {
      setError(null);
      const result = await $typst.svg({ mainContent: source });
      setSvg(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Compilation error');
    }
  }, 500);

  // Compile on content change
  useEffect(() => {
    if (!isLoading) {
      compile(content);
    }
  }, [content, isLoading, compile]);

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="text-center">
          <div className="mb-4 h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent" />
          <p className="text-muted-foreground">Loading Typst compiler...</p>
        </div>
      </div>
    );
  }

  return (
    <ResizablePanelGroup className="h-[calc(100vh-8rem)]">
      <ResizablePanel defaultSize={50} minSize={30}>
        <div className="flex h-full flex-col border-r">
          <div className="border-b bg-muted/50 px-4 py-2">
            <span className="text-sm font-medium">Source</span>
          </div>
          <div className="flex-1 overflow-auto">
            <CodeMirror
              value={content}
              height="100%"
              theme={vscodeDark}
              onChange={(value: string) => setContent(value)}
              className="h-full text-sm [&_.cm-editor]:h-full [&_.cm-scroller]:overflow-auto"
              basicSetup={{
                lineNumbers: true,
                highlightActiveLineGutter: true,
                highlightActiveLine: true,
                foldGutter: false,
              }}
            />
          </div>
        </div>
      </ResizablePanel>

      <ResizableHandle withHandle />

      <ResizablePanel defaultSize={50} minSize={30}>
        <div className="flex h-full flex-col">
          <div className="border-b bg-muted/50 px-4 py-2">
            <span className="text-sm font-medium">Preview</span>
          </div>
          <ScrollArea className="flex-1 bg-white dark:bg-slate-950">
            <div className="p-8">
              {error ? (
                <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
                  <h3 className="mb-2 font-semibold text-destructive">Compilation Error</h3>
                  <pre className="whitespace-pre-wrap text-sm text-destructive/90">{error}</pre>
                </div>
              ) : svg ? (
                <div
                  className="typst-preview"
                  style={{
                    color: 'black',
                    backgroundColor: 'white',
                  }}
                  // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by trusted Typst compiler
                  dangerouslySetInnerHTML={{ __html: svg }}
                />
              ) : (
                <div className="flex h-64 items-center justify-center">
                  <p className="text-muted-foreground">Compiling...</p>
                </div>
              )}
            </div>
          </ScrollArea>
        </div>
      </ResizablePanel>
    </ResizablePanelGroup>
  );
}
