/**
 * @id: structured-document
 * @priority: high
 * @progress: 0
 * @spec: The Intermediate Representation (IR) of a document. A tree/list of ContentBlocks that the Agent manipulates.
 * @skills: ["typescript", "zod"]
 */
export interface StructuredDocument {
    blocks: ContentBlock[];
}

/**
 * @id: content-block
 * @priority: high
 * @progress: 0
 * @spec: Union type for all supported block types in the document.
 * @skills: ["typescript", "zod"]
 */
export type ContentBlock =
    | ParagraphBlock
    | HeadingBlock
    | ListBlock
    | EquationBlock
    | PlotBlock
    | TableBlock;

export interface BaseBlock {
    id: string;
    type: string;
}

export interface ParagraphBlock extends BaseBlock {
    type: 'paragraph';
    text: string;
}

export interface HeadingBlock extends BaseBlock {
    type: 'heading';
    level: 1 | 2 | 3 | 4 | 5 | 6;
    text: string;
}

export interface ListBlock extends BaseBlock {
    type: 'list';
    format: 'bullet' | 'ordered';
    items: string[];
}

/**
 * @id: equation-block
 * @priority: medium
 * @progress: 0
 * @spec: Mathematical equation defined via LaTeX/Math string.
 * @skills: ["typescript"]
 */
export interface EquationBlock extends BaseBlock {
    type: 'equation';
    /**
     * LaTeX or standard math syntax string (e.g. "E = mc^2").
     */
    math: string;
    label?: string;
}

/**
 * @id: plot-block
 * @priority: high
 * @progress: 0
 * @spec: References a ComputeNode that generates a visualization.
 * @skills: ["typescript"]
 */
export interface PlotBlock extends BaseBlock {
    type: 'plot';
    /**
     * ID of the ComputeNode that generates this plot.
     */
    sourceNodeId: string;
    /**
     * Specific output key from the compute node (e.g., "plot_image").
     */
    outputKey: string;
    caption?: string;
}

/**
 * @id: table-block
 * @priority: medium
 * @progress: 0
 * @spec: A table that can be static or dynamic (generated by a ComputeNode).
 * @skills: ["typescript"]
 */
export interface TableBlock extends BaseBlock {
    type: 'table';
    /**
     * If set, data is sourced dynamically from a ComputeNode.
     */
    sourceNodeId?: string;
    outputKey?: string;
    /**
     * Static data if no sourceNodeId is provided.
     */
    rows?: string[][];
    caption?: string;
}
