// Generated by 10xStudent with Bibliography Support
// Date: 2026-02-03T16:45:26.818Z

#set document(title: "Academic Document with Citations", author: "10xStudent User")
#set math.equation(numbering: "(1)")

= Quantum Computing Fundamentals <chap:intro>

Quantum computing was first proposed by Feynman @feynman1982 as a way to simulate quantum systems efficiently.

The field has since evolved significantly, with foundational textbooks @nielsen2010 establishing the theoretical framework.

== Quantum Algorithms

Shor's algorithm @shor1994 demonstrated polynomial-time factoring, threatening current cryptographic systems.

$ |psi angle.r = alpha |0 angle.r + beta |1 angle.r $ <eq:qubit>

The general qubit state shown in @eq:qubit represents a superposition of basis states.

#bibliography("test-references.bib", style: "ieee")