// Generated by 10xStudent IR Transformer
// Date: 2026-02-03T16:42:59.633Z

#set document(title: "Test Document", author: "10xStudent")

// Enable equation numbering for cross-references
#set math.equation(numbering: "(1)")

= Introduction <chap:intro>

This thesis explores the effects of quantum computing on modern cryptography. The implications are significant for future security systems.

== Background <sec:background>

Quantum mechanics provides the foundation for quantum computing#footnote[See Appendix A for mathematical foundations.].

- Superposition allows qubits to exist in multiple states
- Entanglement enables correlated quantum states
- Quantum interference enables computational speedups

$ E = m c^2 $ <eq:einstein>

The famous equation @eq:einstein demonstrates mass-energy equivalence.

#figure(
  table(
    columns: 3,
    [Algorithm], [Classical], [Quantum],
    [Factoring], [O(exp)], [O(poly)],
    [Search], [O(N)], [O(√N)],
  ),
  caption: [Comparison of algorithmic complexity],
) <tbl:complexity>

As shown in @tbl:complexity, quantum algorithms provide significant speedups.

#figure(
  rect(width: 100pt, height: 80pt, fill: gray)[Placeholder: asset-uuid-12345],
  caption: [Quantum Circuit Diagram],
) <fig:circuit>

@fig:circuit illustrates the basic quantum circuit structure.

= Conclusions

This chapter has introduced the fundamental concepts of quantum computing. The following chapters will explore practical applications.