/**
 * Verification Script: StructuredDocument with Bibliography
 * 
 * This script tests that our domain model can produce valid Typst output
 * with citations and a bibliography.
 * 
 * Run with: bun run scripts/verify-typst-bibliography.ts
 */

import { execSync } from 'child_process';
import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';

// Types (simplified)
type ContentBlock = ParagraphBlock | HeadingBlock | EquationBlock;

interface BaseBlock { id: string; type: string; }
interface ParagraphBlock extends BaseBlock { type: 'paragraph'; text: string; }
interface HeadingBlock extends BaseBlock { type: 'heading'; level: 1 | 2 | 3 | 4 | 5 | 6; text: string; label?: string; }
interface EquationBlock extends BaseBlock { type: 'equation'; math: string; label?: string; numbered?: boolean; }

// Document with bibliography (matching our updated Document model)
interface DocumentWithBibliography {
    blocks: ContentBlock[];
    bibliographyPath?: string;  // Simulates bibliographyAssetId resolved to path
    citationStyle?: 'apa' | 'ieee' | 'chicago' | 'mla' | 'harvard';
    metadata?: {
        author?: string;
        supervisor?: string;
        institution?: string;
    };
}

// Transformer
function blockToTypst(block: ContentBlock): string {
    switch (block.type) {
        case 'heading': {
            const hashes = '='.repeat(block.level);
            const label = block.label ? ` <${block.label}>` : '';
            return `${hashes} ${block.text}${label}`;
        }
        case 'paragraph': return block.text;
        case 'equation': {
            const label = block.label ? ` <${block.label}>` : '';
            return `$ ${block.math} $${label}`;
        }
        default: return '// Unknown block';
    }
}

function documentToTypst(doc: DocumentWithBibliography): string {
    const author = doc.metadata?.author || 'Anonymous';
    const preamble = `// Generated by 10xStudent with Bibliography Support
// Date: ${new Date().toISOString()}

#set document(title: "Academic Document with Citations", author: "${author}")
#set math.equation(numbering: "(1)")

`;
    const body = doc.blocks.map(blockToTypst).join('\n\n');

    // Add bibliography at the end if specified
    const bibliography = doc.bibliographyPath
        ? `\n\n#bibliography("${doc.bibliographyPath}", style: "${doc.citationStyle || 'ieee'}")`
        : '';

    return preamble + body + bibliography;
}

// Test document with citations
function createAcademicDocument(): DocumentWithBibliography {
    return {
        blocks: [
            {
                id: 'h1',
                type: 'heading',
                level: 1,
                text: 'Quantum Computing Fundamentals',
                label: 'chap:intro',
            },
            {
                id: 'p1',
                type: 'paragraph',
                text: 'Quantum computing was first proposed by Feynman @feynman1982 as a way to simulate quantum systems efficiently.',
            },
            {
                id: 'p2',
                type: 'paragraph',
                text: 'The field has since evolved significantly, with foundational textbooks @nielsen2010 establishing the theoretical framework.',
            },
            {
                id: 'h2',
                type: 'heading',
                level: 2,
                text: 'Quantum Algorithms',
            },
            {
                id: 'p3',
                type: 'paragraph',
                text: "Shor's algorithm @shor1994 demonstrated polynomial-time factoring, threatening current cryptographic systems.",
            },
            {
                id: 'eq1',
                type: 'equation',
                math: '|psi angle.r = alpha |0 angle.r + beta |1 angle.r',
                label: 'eq:qubit',
                numbered: true,
            },
            {
                id: 'p4',
                type: 'paragraph',
                text: 'The general qubit state shown in @eq:qubit represents a superposition of basis states.',
            },
        ] as ContentBlock[],
        bibliographyPath: 'test-references.bib',
        citationStyle: 'ieee',
        metadata: {
            author: '10xStudent User',
            supervisor: 'Prof. Example',
            institution: 'University of Technology',
        },
    };
}

async function main() {
    console.log('🔬 StructuredDocument with Bibliography Verification\n');
    console.log('='.repeat(50));

    const testDoc = createAcademicDocument();
    console.log(`✅ Created academic document with ${testDoc.blocks.length} blocks`);
    console.log(`   Bibliography: ${testDoc.bibliographyPath}`);
    console.log(`   Citation style: ${testDoc.citationStyle}`);

    const typstContent = documentToTypst(testDoc);
    console.log('✅ Transformed IR to Typst');

    const tempTypstFile = join(__dirname, 'test-academic.typ');
    const tempPdfFile = join(__dirname, 'test-academic.pdf');

    writeFileSync(tempTypstFile, typstContent);
    console.log(`✅ Wrote Typst file: ${tempTypstFile}`);

    console.log('\n📄 Generated Typst Content:');
    console.log('-'.repeat(50));
    console.log(typstContent);
    console.log('-'.repeat(50));

    console.log('\n🔧 Compiling with Typst CLI...');
    try {
        // Compile from scripts directory so relative paths work
        execSync(`typst compile "${tempTypstFile}" "${tempPdfFile}"`, {
            stdio: 'pipe',
            cwd: __dirname,
        });
        console.log('✅ Typst compilation SUCCESSFUL!');
        console.log(`📁 Output PDF: ${tempPdfFile}`);

        if (existsSync(tempPdfFile)) {
            console.log('✅ PDF file with bibliography generated successfully');
        }
    } catch (error) {
        console.error('❌ Typst compilation FAILED!');
        if (error instanceof Error && 'stderr' in error) {
            console.error('Error output:', (error as { stderr: Buffer }).stderr.toString());
        }
        process.exit(1);
    }

    console.log('\n' + '='.repeat(50));
    console.log('🎉 BIBLIOGRAPHY VERIFICATION PASSED!');
    console.log('='.repeat(50));

    console.log('\n🏷️  Bibliography Features Tested:');
    console.log('   - BibTeX bibliography file (.bib)');
    console.log('   - Inline citations (@key)');
    console.log('   - IEEE citation style');
    console.log('   - Document metadata (author, institution)');
    console.log('   - Numbered equations with cross-references');
}

main();
