import { z } from "zod";
import { sourceTypeSchema } from "./source-type";

// Base Source Schema (Shared properties)
export const sourceBaseSchema = z.object({
  id: z.uuid(),
  documentId: z.uuid(),
  url: z.url(),
  citationKey: z.string().min(1, "Citation key is required"), // Critical for Typst linkage
  title: z.string().optional(),
  author: z.string().optional(),
  publicationDate: z.iso.datetime().optional(), // ISO string
  sourceType: sourceTypeSchema,
});

// Create Source Input Schema (Client side)
export const createSourceSchema = sourceBaseSchema.omit({
  id: true,
  citationKey: true, // Generated by backend
  sourceType: true, // Auto-detected by backend if missing
}).extend({
  citationKey: z.string().optional(), // Optional override
  sourceType: sourceTypeSchema.optional(),
  content: z.string().optional(), // For RAG/Preview
});

// Update Source Input Schema
export const updateSourceSchema = sourceBaseSchema.partial().omit({
  id: true,
  documentId: true,
});

// Full Source Type (Database/API Response)
export type Source = z.infer<typeof sourceBaseSchema> & {
  content?: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type CreateSourceInput = z.infer<typeof createSourceSchema>;
export type UpdateSourceInput = z.infer<typeof updateSourceSchema>;
